### ISSUE TITLE
BUG 3 Cores only if used SDK non AX58

### ISSUE THREAD

**Issue by CrashX** [SWRT-dev/Supported_Devices#10]
I tested on several user devices, there the 3rd core is not blocked

300438645898 Work All cores
300438647029 Work All cores
300438648631 Work All cores
300438648908 Work All cores

you probably used sources from TUF/AX82/GS
if you try to convert the router to another model, then the 3rd core is disabled

TUF3000 at 99 corresponds to the AX58 model, but there are probably some mechanisms that determine the substitution and disable the 3rd core

I thought that they introduced protection against cross-firmware and changing the factory nvram was not enough

I do cross-firmware, and before that I change the factory nvram so that the model is 100% functional and can be updated to stock firmware (russian lang > https://urouter.ru/lab/crossflash-rt-ac86u-to-gt-ac2900.html )

_Originally posted by @CrashX in https://github.com/SWRT-dev/Supported_Devices/issues/9#issuecomment-1166184524_

**Comment by paldier** [comment]
The last core of 675x/685x/491x series for offloading only(wan2lan and wan2wlan). There is no information that ASUS will modify that.
