### ISSUE TITLE
Wrong Firmware Uploaded for RT AX-86U

### ISSUE THREAD

**Issue by F4Mask** [SWRT-dev/Supported_Devices#20]
i notice that for the ax86u firmware in MEGA, the latest firware is for ax86u pro..

please upload the right firmware for ax86u.. thank you : )

![Screenshot (11)](https://github.com/SWRT-dev/Supported_Devices/assets/166966011/fffb5722-93a3-423d-a4f1-244b948b58c1)

**Comment by paldier** [comment]
thanks, i have uploaded correct firmware
