### ISSUE TITLE
Kernel Update on RAX120v2

### ISSUE THREAD

**Issue by xgeo23** [SWRT-dev/Supported_Devices#22]
the last compilation of SWRT have an older Kernel, and that causes the pppoe not to work, despite having everything configured correctly, it does not connect and it is because the kernel is old

**Comment by paldier** [comment]
do you know what you are talking about

**Comment by xgeo23** [comment]
sorry about that, forget about the kernel, i only want to report pppoe not working on RAX120v2 despite having everything configured correctly, it does not connect
