### ISSUE TITLE
Bug RT-AX58U

### ISSUE THREAD

**Issue by CrashX** [SWRT-dev/Supported_Devices#9]
This firmware uses only 2 processor cores
3rd core is not used at all

openssl speed -multi 3 -evp aes-128-cbc
evp              55209.62k    62520.84k    73690.32k    75313.70k    74623.69k    73788.07k
load olny 2 cores

stock
openssl speed -multi 3 -evp aes-128-cbc
evp 83126.74k 103317.03k 111478.10k 111467.86k 112967.95k 112306.86k

**Comment by paldier** [comment]
asus set the last core to be used only for wifi, all 675x series. If asus changes it in the next version of the gpl code, i will merge it.

**Comment by CrashX** [comment]
it's not quite right

I'm 100% sure you used sources from TUF-AX3000 V1
which is 99% hardware compatible

because I do not compile the firmware and do the flashing
Let me explain, my AC86 has been converted to GT2900 for several years
and works on official firmware (russian lang > https://urouter.ru/lab/crossflash-rt-ac86u-to-gt-ac2900.html )

I did the same with AX58, but even on the oldest firmware TUF OR GS the 3rd core is not available
